dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:snaipewastaken/ppa'
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - libyaml-dev
      - protobuf-compiler
      - protobuf-c-compiler
      - criterion-dev
      - criterion
      - cmake

branches:
  only:
  - master
  - dev

language: c

compiler: gcc

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --extra-verbose
